### PR TITLE
[closes #52] Get rid of tree job flow

### LINKED ISSUE #52: Get rid of tree job flow
All phase annotations have attribute "parent" (annotated with `@ParentId`) now. But jenkins test executor does not require it.  It would be useful if we wanted to have a tree structure with several possible roots. But we do not need this. It is sufficient for us to execute every phase only once in proper order - flat job flow. There is just one exception when you inject objects to method parameters and there are several possible objects to inject.

### PR DESCRIPTION
**Pull request by basovnik**

### CODE REVIEW

File: src/main/java/org/jboss/qa/jenkins/test/executor/property/ContextPropertyResolver.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+import java.util.List;
+
+import lombok.extern.slf4j.Slf4j;
+
+@Slf4j
+public class ContextPropertyResolver implements PropertyResolver {
+
+	@Override
+	public String resolve(String name) {
+		final List<Object> objs = InstanceRegistry.get(Context.class);
```
Comment (osmman) [inline src/main/java/org/jboss/qa/jenkins/test/executor/property/ContextPropertyResolver.java]: Deprecated

File: src/main/java/org/jboss/qa/jenkins/test/executor/utils/JenkinsUtils.java [hunk 2]
```diff
@@ -27,9 +31,19 @@
 	private JenkinsUtils() {
 	}
 
+	public static File getWorkspace() {
+		final List<Object> objs = InstanceRegistry.get(Workspace.class);
```
Comment (osmman) [inline src/main/java/org/jboss/qa/jenkins/test/executor/utils/JenkinsUtils.java]: Deprecated

**Comment by osmman** [comment]
Personally, I would use a builder pattern for Class DefaultValuePropertyReplacer. You can use this [1] diff.

[1] https://gist.github.com/osmman/05a83579cb3a52d9bd69
